CREATE TABLE IF NOT EXISTS Emails (
    ID SERIAL PRIMARY KEY,
    Email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PhoneNumbers (
    ID SERIAL PRIMARY KEY,
    Phone VARCHAR(20) NOT NULL
);

CREATE ROLE ${DB_REPL_USER} WITH REPLICATION PASSWORD '${DB_REPL_PASSWORD}' LOGIN;
ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
